### PR TITLE
Support Mnemonic Phrase passwords

### LINKED ISSUE #128: Add password support for Mnemonics
Make it optional but include a warning that non-password protected mnemonics are less secure.

### PR DESCRIPTION
**Pull request by QuestofIranon**
This enables users to create and access a accounts using a password protected mnemonic phrase.

Screenshot_2019-11-19 MyHbarWallet(1)

Screenshot_2019-11-19 MyHbarWallet(1)

closes #128

### CODE REVIEW

**Comment by QuestofIranon** [comment]
At a loss as to why this is failing ->

```
2:05:11 AM:   ● OptionalPasswordInput › renders
2:05:11 AM:     TypeError: Cannot read property 'showPassword' of undefined
2:05:11 AM:       65 |         function handleInput(password: string): void {
2:05:11 AM:       66 |             context.emit("input", password);
2:05:11 AM:     > 67 |         }
2:05:11 AM:          |          ^
2:05:11 AM:       68 |
2:05:11 AM:       69 |         function handleToggleDisplay(show: boolean): void {
2:05:11 AM:       70 |             state.showPassword = show;
2:05:11 AM:       at Proxy.render (src/components/OptionalPasswordInput.vue:67:581)
2:05:11 AM:       at VueComponent.Vue._render (node_modules/vue/dist/vue.runtime.common.dev.js:3532:22)
2:05:11 AM:       at VueComponent.updateComponent (node_modules/vue/dist/vue.runtime.common.dev.js:4048:21)
2:05:11 AM:       at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:4459:25)
2:05:11 AM:       at new Watcher (node_modules/vue/dist/vue.runtime.common.dev.js:4448:12)
2:05:11 AM:       at mountComponent (node_modules/vue/dist/vue.runtime.common.dev.js:4055:3)
2:05:11 AM:       at VueComponent.Object.<anonymous>.Vue.$mount (node_modules/vue/dist/vue.runtime.common.dev.js:8386:10)
2:05:11 AM:       at init (node_modules/vue/dist/vue.runtime.common.dev.js:3112:13)
2:05:11 AM:       at createComponent (node_modules/vue/dist/vue.runtime.common.dev.js:5952:9)
2:05:11 AM:       at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:5899:9)
2:05:11 AM:       at VueComponent.patch [as __patch__] (node_modules/vue/dist/vue.runtime.common.dev.js:6449:7)
2:05:11 AM:       at VueComponent.Vue._update (node_modules/vue/dist/vue.runtime.common.dev.js:3927:19)
```

**Comment by mehcode** [comment]
@QuestofIranon @cacampbell Can we follow up here and get this finished?

**Comment by QuestofIranon** [comment]
on it

**Comment by QuestofIranon** [comment]
@donaldthibeau @atul-hedera 
Awaiting approval to add password support for mnemonic phrases.

**Pull request merged**
