### PR TITLE
Implement Offline Transactions

### PR DESCRIPTION
**Pull request by danielakhterov**
- Implement transaction hex output for send transfer
    - Create `InterfaceSignExecute`
    - Implement signing of tx hex string with private key
    - Implement executing of tx hex string

### CODE REVIEW

**Comment by mehcode** [comment]
This should not be merged into master. Let's make a develop branch.

**Comment by danielakhterov** [comment]
> This should not be merged into master. Let's make a develop branch.

Created `develop` branch, and updated PR base.

**Comment by danielakhterov** [comment]
Accidentally rebased onto master, but still pointing to develop. ¯\_(ツ)_/¯

**Comment by mehcode** [comment]
@danielakhterov Please re-open against `master`

**Pull request closed without merging**
