### PR TITLE
fixed header styling on interface

### PR DESCRIPTION
**Pull request by Austin-Shep**
hamburger button needed different styling on the interface, added a check to compensate. tested on galaxy s8 active and chrome mobile dev tools

### CODE REVIEW

**Comment by Austin-Shep** [comment]
#172

**Comment by cacampbell** [comment]
image
image


Cut off on the right for non-mobile (tablet+) views. Is that new? If so, fix, if not, new issue (and I'll approve, looks good otherwise)

**Comment by Austin-Shep** [comment]
@cacampbell do we have a tablet to test on? i don't quite trust that view for "real-world" looks. i didn't get that clipping when i tested it but it's hard to be sure.

**Comment by cacampbell** [comment]
we do not? I think? and yeah it does kindof seem like a browser view problem.

**Pull request merged**
